const actionTypes = {

    FAILURE: 'FAILURE',
    ADD_TODO: 'ADD_TODO',
    TOOGLE_TODO: 'TOOGLE_TODO',

    SET_VISIBILITY_FILTER:'SET_VISIBILITY_FILTER',
    SHOW_ALL: 'SHOW_ALL',
    SHOW_COMPLETED: 'SHOW_COMPLETED',
    SHOW_ACTIVE: 'SHOW_ACTIVE',

    FETCH_TODOS_BEGIN: 'FETCH_TODOS_BEGIN',
    FETCH_TODOS_SUCCESS: 'FETCH_TODOS_SUCCESS',
    FETCH_TODOS_FAILURE: 'FETCH_TODOS_FAILURE',
    

}

export default actionTypes;
